apiVersion: v1
kind: Service
metadata:
  name: document-service
spec:
  selector:
    app: document-app
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-app
spec:
  selector:
    matchLabels:
      app: document-app
  replicas: 2
  template:
    metadata:
      labels:
        app: document-app
    spec:
      containers:
      - name: restapi-document
        image: manfranmon/restapi-document:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000